version: '3.8'
services:
  mongodb:
    image: mongo
    ports:
      - '27017:27017'
    networks:
      - bazanet

  web:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/vet_clinic
    networks:
       - bazanet
networks:
  bazanet:
    driver: bridge